# Generated by Django 2.2.5 on 2020-03-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='atualizado',
        ),
        migrations.AddField(
            model_name='cargo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='servico',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Modificado'),
        ),
    ]
